on: [push, pull_request]

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: yarn test